ci: run apt-get update before running mkosi
This is alternative to https://github.com/systemd/mkosi/commit/8c9f6cc6586c4f3b8fedafc5a19e6bf30531ebfc

The repository metadata in the image can get out of date. Let's run
apt-get update to make sure it is fresh.

```
Err:21 https://security.ubuntu.com/ubuntu noble-updates/main amd64 libboost-thread1.83.0 amd64 1.83.0-2.1ubuntu3.1
  404  Not Found [IP: 52.161.185.214 80]
E: Failed to fetch https://security.ubuntu.com/ubuntu/pool/main/b/boost1.83/libboost-thread1.83.0_1.83.0-2.1ubuntu3.1_amd64.deb  404  Not Found [IP: 52.161.185.214 80]
Fetched 8320 kB in 2s (3488 kB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

rhel-only: ci
Related: RHEL-155394